### ISSUE TITLE
Angles.js dep

### ISSUE THREAD

**Issue by infusion** [wikipathways/gpml2pvjson-js#10]
Hi,

I'm the author of the angles.js library you use. It's totally fine to use the library the way you do, but I wonder if you could give some feedback about it. Did you decide to convert the source to typescript since no type information are given? I never used typescript, but would it help to ship a `.d.ts` file for type annotations or what was the reason to go this way? I'd like to make all of my projects typescript save, so it would be nice to learn your rationale.

Thanks Robert

**Comment by ariutta** [comment]
Hi Robert,

Thanks for creating Angles.js! I believe the only (?) reason I converted it to TS was so I could benefit from tree shaking:
https://webpack.js.org/guides/tree-shaking/
https://github.com/rollup/rollup#tree-shaking

Since Angles uses an IIFE, I think right now either the entire library is included in a bundle or nothing is. It's not super big, so maybe that doesn't matter too much.

**Comment by infusion** [comment]
Ah, okay for tree-shaking it totally makes sense. Reason for IIFE is a capsule for users who want to use it via bower or directly in the browser. I will create a solid build system for all of my libs under the new constraints (require.js, es6 modules, typescript annotations, es5 export for browsers + closure compiler optimizations and a way to make tree-shaking work). Thanks for the quick response! I will ping you when these things are resolved, if you want.

**Comment by ariutta** [comment]
Sure let me know, thanks! And yes, `.d.ts` definitions would be great. Feel free to use my file as a starting point.
